#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : kimageformats
Version  : 5.50.0
Release  : 2
URL      : https://download.kde.org/stable/frameworks/5.50/kimageformats-5.50.0.tar.xz
Source0  : https://download.kde.org/stable/frameworks/5.50/kimageformats-5.50.0.tar.xz
Summary  : No detailed summary available
Group    : Development/Tools
License  : LGPL-2.1
Requires: kimageformats-lib
Requires: kimageformats-license
Requires: kimageformats-data
BuildRequires : buildreq-cmake
BuildRequires : buildreq-kde

%description
# KImageFormats
Plugins to allow QImage to support extra file formats.
## Introduction

%package data
Summary: data components for the kimageformats package.
Group: Data

%description data
data components for the kimageformats package.


%package lib
Summary: lib components for the kimageformats package.
Group: Libraries
Requires: kimageformats-data
Requires: kimageformats-license

%description lib
lib components for the kimageformats package.


%package license
Summary: license components for the kimageformats package.
Group: Default

%description license
license components for the kimageformats package.


%prep
%setup -q -n kimageformats-5.50.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1536422596
mkdir clr-build
pushd clr-build
%cmake ..
make  %{?_smp_mflags}
popd

%install
export SOURCE_DATE_EPOCH=1536422596
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/kimageformats
cp COPYING.LIB %{buildroot}/usr/share/doc/kimageformats/COPYING.LIB
pushd clr-build
%make_install
popd

%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/kservices5/qimageioplugins/dds.desktop
/usr/share/kservices5/qimageioplugins/eps.desktop
/usr/share/kservices5/qimageioplugins/jp2.desktop
/usr/share/kservices5/qimageioplugins/kra.desktop
/usr/share/kservices5/qimageioplugins/ora.desktop
/usr/share/kservices5/qimageioplugins/pcx.desktop
/usr/share/kservices5/qimageioplugins/pic.desktop
/usr/share/kservices5/qimageioplugins/psd.desktop
/usr/share/kservices5/qimageioplugins/ras.desktop
/usr/share/kservices5/qimageioplugins/rgb.desktop
/usr/share/kservices5/qimageioplugins/tga.desktop
/usr/share/kservices5/qimageioplugins/xcf.desktop

%files lib
%defattr(-,root,root,-)
/usr/lib64/qt5/plugins/imageformats/kimg_eps.so
/usr/lib64/qt5/plugins/imageformats/kimg_kra.so
/usr/lib64/qt5/plugins/imageformats/kimg_ora.so
/usr/lib64/qt5/plugins/imageformats/kimg_pcx.so
/usr/lib64/qt5/plugins/imageformats/kimg_pic.so
/usr/lib64/qt5/plugins/imageformats/kimg_psd.so
/usr/lib64/qt5/plugins/imageformats/kimg_ras.so
/usr/lib64/qt5/plugins/imageformats/kimg_rgb.so
/usr/lib64/qt5/plugins/imageformats/kimg_tga.so
/usr/lib64/qt5/plugins/imageformats/kimg_xcf.so

%files license
%defattr(-,root,root,-)
/usr/share/doc/kimageformats/COPYING.LIB
